Repository 404-DriverNotFound/200-OK, pull requests merged in 2021-05, with the labels that each got.

#23 Refact: 메인문 수정, Webserv 클래스 추가, Select 함수 추가
  Makefile
  srcs/Buffer/Buffer.cpp
  srcs/Buffer/Buffer.hpp
  srcs/Client/Client.cpp
  srcs/Client/Client.hpp
  srcs/HttpMessage/HttpMessageRequest.cpp
  srcs/HttpMessage/HttpMessageRequest.hpp
  srcs/Server/Socket.cpp
  srcs/Server/Socket.hpp
  srcs/Socket.cpp
  srcs/Utils/utils.cpp
  srcs/Utils/utils.hpp
  srcs/Webserver/Webserver.cpp
  srcs/Webserver/Webserver.hpp
  srcs/main.cpp
Labels: enhancement

#24 Refactor: bases_* 폴더에 있는 코드를 srcs에 폴더별로 분류함.
  base_headers/Buffer.hpp
  base_headers/Client.hpp
  base_headers/Socket.hpp
  base_headers/Webserver.hpp
  base_headers/all_header.hpp
  base_headers/utils.hpp
  base_srcs/utils.cpp
  gnl/get_next_line_bonus.cpp
  gnl/get_next_line_bonus.hpp
  gnl/get_next_line_utils_bonus.cpp
  srcs/Config/Config.cpp
  srcs/Config/Config.hpp
  srcs/Path/Path.cpp
  srcs/Path/Path.hpp
  srcs/Server/Server.cpp
  srcs/Server/Server.hpp
  srcs/ServerParsing/Makefile
  srcs/ServerParsing/ServerConfigIdx.hpp
  srcs/Utils/utils.cpp
  srcs/Utils/utils.hpp
  yunslee_test/server_parsing/Path_function.cpp
  yunslee_test/server_parsing/Path_test.cpp
  yunslee_test/server_parsing/ReplaceAll.cpp
  yunslee_test/server_parsing/ft_split_vector.cpp
  yunslee_test/server_parsing/parsing1
  yunslee_test/server_parsing/parsing_example.cpp
  yunslee_test/server_parsing/server_config2
  yunslee_test/복사 창고.hpp
Labels: Reactoring

#28 Feat: Combine/configparsing
  .vscode/launch.json
  .vscode/settings.json
  Makefile
  srcs/Config/Config.cpp
  srcs/Config/Config.hpp
  srcs/Config/Configs.cpp
  srcs/Config/Configs.hpp
  srcs/Path/Path.cpp
  srcs/Path/Path.hpp
  srcs/Server/Server.cpp
  srcs/Server/Server.hpp
  srcs/Server/Servers.cpp
  srcs/Server/Servers.hpp
  srcs/Server/Socket.cpp
  srcs/Server/Socket.hpp
  srcs/ServerParsing/ServerConfigIdx.cpp
  srcs/ServerParsing/ServerConfigIdx.hpp
  srcs/Webserver/Webserver.cpp
  srcs/Webserver/Webserver.hpp
  srcs/main.cpp
  webserv.config
Labels: enhancement

#30 Feat: main 함수 추가
  Makefile
  srcs/ServerManager.cpp
  srcs/ServerManager.hpp
  srcs/main.cpp
Labels: enhancement

#32 Feat: createServer 함수 추가
  Makefile
  srcs/Config.cpp
  srcs/Config.hpp
  srcs/Location.cpp
  srcs/Location.hpp
  srcs/Server.cpp
  srcs/Server.hpp
  srcs/ServerManager.cpp
  srcs/ServerManager.hpp
  srcs/main.cpp
Labels: enhancement, help wanted

#37 Feat: Connection class 및 소켓프로그래밍 뼈대에 select 기능추가 및 Keep alive demo 버전 구현
  Makefile
  srcs/Connection.cpp
  srcs/Connection.hpp
  srcs/Define.hpp
  srcs/Request.hpp
  srcs/Response.hpp
  srcs/Server.cpp
  srcs/Server.hpp
  srcs/ServerManager.cpp
  srcs/ServerManager.hpp
  srcs/main.cpp
  webserv
Labels: enhancement

#45 Feat/connection class
  Makefile
  autoindex_example.html
  error_example.html
  srcs/Connection.cpp
  srcs/Connection.hpp
  srcs/Define.hpp
  srcs/Response.cpp
  srcs/Response.hpp
  srcs/Server.cpp
  srcs/Server.hpp
  srcs/ServerManager.cpp
  srcs/ServerManager.hpp
  srcs/Utils/utils.cpp
  srcs/Utils/utils.hpp
  srcs/main.cpp
Labels: enhancement

#46 Feat/response
  error_example.html
  srcs/Connection.cpp
  srcs/Connection.hpp
  srcs/Response.cpp
  srcs/Response.hpp
  srcs/Server.cpp
  srcs/Server.hpp
  srcs/ServerConfigIdx/ServerConfigIdx.cpp
  srcs/ServerConfigIdx/ServerConfigIdx.hpp
  srcs/ServerManager.cpp
  srcs/Utils/utils.cpp
  srcs/Utils/utils.hpp
Labels: enhancement

#47 Feat/recvRequest
  srcs/Connection.cpp
  srcs/Connection.hpp
  srcs/Define.hpp
  srcs/Request.cpp
  srcs/Request.hpp
  srcs/Server.cpp
  srcs/Server.hpp
  srcs/ServerManager.cpp
  srcs/Utils/utils.cpp
  srcs/Utils/utils.hpp
Labels: bug

#49 Fix/parse startLine uri 파싱부분 수정
  srcs/Location.hpp
  srcs/Request.cpp
  srcs/Request.hpp
  srcs/Server.cpp
  srcs/ServerManager.cpp
Labels: bug

#55 Feat/configfile
  Makefile
  default.config
  default2.config
  srcs/ConfigFile/ConfigFile.cpp
  srcs/ConfigFile/ConfigFile.hpp
  srcs/ConfigFile/ConfigFiles.cpp
  srcs/Server.cpp
  srcs/Server.hpp
  srcs/ServerConfigIdx/ServerConfigIdx.cpp
  srcs/ServerManager.cpp
  srcs/Server_execute*.cpp
  srcs/Server_parsing.cpp
  srcs/Server_run.cpp
Labels: Reactoring, enhancement

#56 Feat/method
  Makefile
  default.config
  srcs/ConfigFile/ConfigFile.cpp
  srcs/Path/Path.cpp
  srcs/Path/Path.hpp
  srcs/Response.cpp
  srcs/Response.hpp
  srcs/Server.cpp
  srcs/Server.hpp
  srcs/Server_execute*.cpp
  srcs/Server_parsing.cpp
  srcs/Server_run.cpp
  srcs/Utils/utils.cpp
Labels: enhancement

#59 Refact/step1
  default.config
  default2.config
  default3.config
  index.html
  srcs/Response.cpp
  srcs/Response.hpp
  srcs/Server.cpp
  srcs/Server.hpp
  srcs/Server_execute*.cpp
  srcs/Server_run.cpp
  srcs/Utils/utils.cpp
  srcs/Utils/utils.hpp
Labels: Reactoring

#77 Feat/host
  default.config
  srcs/ConfigFile/ConfigFile.cpp
  srcs/ConfigFile/ConfigFile.hpp
  srcs/ConfigFile/ConfigFiles.cpp
  srcs/Request.cpp
  srcs/Server.cpp
  srcs/Server.hpp
  srcs/ServerConfigIdx/ServerConfigIdx.cpp
  srcs/ServerManager.cpp
  srcs/ServerManager.hpp
  srcs/Server_parsing.cpp
  srcs/Server_run.cpp
  srcs/main.cpp
  test.config
  test_host.config
Labels: enhancement

#81 Fix: host, port, server_name의 일치여부를 위한 STL를 set->vector로 수정함
  srcs/ServerManager.cpp
Labels: Reactoring

#82 Feat/update max fd
  srcs/Server.cpp
  srcs/ServerManager.cpp
  srcs/ServerManager.hpp
  srcs/Server_run.cpp
  srcs/main.cpp
Labels: Reactoring, enhancement

#83 Feat: 맨 뒤에 슬래쉬에 따라서 폴더인지 파일인지 그리고 리디렉션
  YoupiBanane/directory/oulalala/a
  srcs/Request.cpp
  srcs/Response.cpp
  srcs/Server.cpp
  srcs/Server_execute*.cpp
  srcs/Utils/utils.cpp
  srcs/Utils/utils.hpp
  test.config
Labels: enhancement
